module.exports = [
    "Is an argument between two vegans still called a beef?"
  , "If a 99 pound person eats 1 pound of nachos, does that make them 1 percent nacho?"
  , "If two witches watched two watches, which witch would watch which watch?"
  , "If vegetarians are trying to save the animals, why are they eating their food?"
  , "If a vampire bites a zombie, will the vampire turn into a zombie, or the zombie turn into a vampire?"
  , "If you accuse yourself in the game of Clue, and are correct, did you win, or lose?"
  , "If you put Lil Wayne and Lil John together, do you get a full size John Wayne?"
  , "I wonder how many animals we jumped on the backs of before we learned that horses were cool with it?"
  , "If you are lost in the middle of nowhere, how do you know that you are in the middle?"
  , "If humans are 70 percent water and humans drink water, does that make us cannibals?"
  , "If Cinderella's shoe fit perfectly, why did it fall off?"
  , "Wouldn't it be ironic if you died in your living room?"
  , "If pro is the opposite of con, what is the opposite of progress?"
  , "If you are waiting for the waiter, doesn't that make you the waiter?"
  , "If camera lenses are round, why do pictures come out rectangular?"
  , "If we are not suppose to have midnight snacks, why does the refrigerator have a light inside?"
  , "If we call a drink a drink, why don't we call food an eat?"
  , "If you sleep like a baby, does that mean you wake up every two hours crying?"
  , "The genie says that I can't wish for more wishes, but never said that I can't wish for more genies."
  , "If a deaf person goes to court, is it still a hearing?"
  , "Why are they called apartments if they are packed so close together?"
  , "If your vacuum cleaner gets dirty and you have to clean it, does that make you the vacuum cleaner?"
  , "If someone's life was saved, shouldn't we say instead that someone's death was postponed?"
  , "If Jesus could walk on water and humans are 78 percent water, if I walk on someone, does that make me 78% Jesus?"
  , "If Apple made a car, would it have windows?"
  , "If a couple breaks off an engagement, is it called a near missus?"
  , "If the pope dies, is he promoted, or fired?"
  , "Once you read the dictionary, every other book is a remix."
  , "If time is money, then are A T M's, time machines?"
  , "If Barbie is so popular, why do you have to buy her friends?"
  , "What do golfers do when they retire?"
  , "If actions are stronger than words, then why is the pen mightier than the sword?"
  , "If Iron Man and Silver Surfer teamed up, would they be alloys?"
  , "If good things come to those who wait, isn't procrastination a virtue?"
  , "If a word in the dictionary is misspelled, how would we know?"
  , "If you are a security guard at a Samsung store, does that make you guardian of the galaxies?"
  , "If it is zero degrees outside, and the weatherman says it will be twice as cold tomorrow, what tempearture will it be?"
  , "Why do noses run, while feet smell?"
  , "If a car travels at the speed of light, what happens when you turn on the headlights?"
  , "Is it possible for fat people to skinny dip?"
  , "Was the invention of the shovel, ground breaking?"
  , "If swearing is immature, why is referred to as 'adult language'?"
  , "If I am nobody, and nobody is perfect, am I perfect?"
  , "If tomatoes are a fruit, isn't ketchup technically a smoothie?"
  , "If the point of golf is to hit the ball the fewest number of times, does not playing, mean that you always win?"
  , "If you download a movie illegally in Jamaica, does that make you a priate of the caribeean?"
  , "If two mind readers read each others minds, wouldn't they be reading their own minds?"
  , "Who coined the phrase, coined the phrase?"
  , "Do the transformers have car insurance, or health insurance?"
  , "If three out of five smokers die from smoking, are the other two immortal?"
  , "If a red head works at a bakery, does that make him a ginger bread man?"
];
